Update update-hosts.js
Fix error when adding host file entries

```
Error: Command failed: /Users/admin/Library/Caches/fnm_multishells/2098_1687516908456/bin/node /Users/admin/Library/Application Support/fnm/node-versions/v18.16.0/installation/lib/node_modules/wp-local-docker/hosts.js add gus.local
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module '/Users/admin/Library/Application'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.16.0

    at /Users/admin/Library/Application Support/fnm/node-versions/v18.16.0/installation/lib/node_modules/wp-local-docker/node_modules/sudo-prompt/index.js:390:27
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  code: 1
}
⚠ Something went wrong adding host file entries. You may need to add the /etc/hosts entries manually.
```